create or replace VIEW CONSUMPTION.ATTENDANCE_FSM
AS
SELECT
    fsm.TERM_KEY,
    terms.APPROXIMATE_TERM_START_DATE,
	GEOGRAPHIC_LEVEL,
	COUNTRY_CODE,
	REGION_CODE,
    REGION_NAME,
	LA_CODE,
    LA_NAME,
	DISADVANTAGE_CODE,
	FREE_SCHOOL_MEAL_ELIGIBLE,
	OVERALL_ATTENDANCE,
	OVERALL_ABSENCE,
	ATTENDANCE_PERC,
	OVERALL_ABSENCE_PERC,
	ILLNESS_PERC,
	APPOINTMENTS_PERC,
	UNAUTH_HOL_PERC,
	UNAUTH_OTH_PERC,
	AUTH_RELIGIOUS_PERC
FROM CURATED.ATTENDANCE_FSM fsm
JOIN CURATED.TERMS terms
on terms.TERM_KEY = fsm.TERM_KEY;

create or replace view CONSUMPTION.LOCAL_AUTHORITIES
as
SELECT
	LA_CODE,
	LA_NAME,
	OLD_LA_CODE,
	REGION_CODE
FROM CURATED.LOCAL_AUTHORITIES;

create or replace view CONSUMPTION.REGIONS
AS
SELECT
	REGION_CODE,
	REGION_NAME,
	COUNTRY_CODE
FROM CURATED.REGIONS;

create or replace view CONSUMPTION.TERMS
AS
SELECT
	TERM_KEY,
	TIME_PERIOD,
	TIME_IDENTIFIER,
	APPROXIMATE_TERM_START_DATE
FROM CURATED.TERMS;