 create or replace dynamic table CURATED.ATTENDANCE_FSM
TARGET_LAG = '1 minute'
WAREHOUSE = TRANSFORMATION_WH
as
select 
    TIME_PERIOD, 
    TIME_IDENTIFIER, 
    case 
        when TIME_IDENTIFIER = 'Autumn term'
        then to_date(substr(TIME_PERIOD,0,4) || '-09-01')
        when TIME_IDENTIFIER = 'Spring term' 
        then to_date(substr(TIME_PERIOD,0,2) || substr(TIME_PERIOD,5,6) || '-01-01')
        when TIME_IDENTIFIER = 'Summer term' 
        then to_date(substr(TIME_PERIOD,0,2) || substr(TIME_PERIOD,5,6) || '-04-14')
    end as APPROXIMATE_TERM_START_DATE,
    GEOGRAPHIC_LEVEL,
    COUNTRY_CODE,
    REGION_CODE,
    REGION_NAME,
    NEW_LA_CODE as LA_CODE,
    LA_NAME,
    DISADVANTAGE_CODE,
    DISADVANTAGE_CODE = 'FSM eligible' as FREE_SCHOOL_MEAL_ELIGIBLE,
    TO_NUMBER(OVERALL_ATTENDANCE) as OVERALL_ATTENDANCE,
    TO_NUMBER(OVERALL_ABSENCE) as OVERALL_ABSENCE,
    TO_DOUBLE(ATTENDANCE_PERC) as ATTENDANCE_PERC,
    TO_DOUBLE(OVERALL_ABSENCE_PERC) as OVERALL_ABSENCE_PERC,
    TO_DOUBLE(ILLNESS_PERC) as ILLNESS_PERC,
    TO_DOUBLE(APPOINTMENTS_PERC) as APPOINTMENTS_PERC,
    TO_DOUBLE(UNAUTH_HOL_PERC) as UNAUTH_HOL_PERC,
    TO_DOUBLE(UNAUTH_OTH_PERC) as UNAUTH_OTH_PERC,
    TO_DOUBLE(AUTH_RELIGIOUS_PERC) as AUTH_RELIGIOUS_PERC
from STAGING.STG_ATTENDANCE_FSM fsm
WHERE OVERALL_ATTENDANCE != 'c';