USE SCHEMA STAGING;

CREATE STAGE INTERNAL_STAGE DIRECTORY = ( ENABLE = true );

create or replace file format CSV_SKIP_HEADER TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"';

SELECT t.$1, t.$2 FROM @INTERNAL_STAGE/data/aut_fsm.csv (file_format => 'CSV_SKIP_HEADER') t;

copy into STG_ATTENDANCE_FSM from @INTERNAL_STAGE/data/aut_fsm.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_SKIP_HEADER');

copy into STG_ATTENDANCE_FSM from @INTERNAL_STAGE/data/spr_fsm.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_SKIP_HEADER');

copy into STG_ATTENDANCE_FSM from @INTERNAL_STAGE/data/sum_fsm.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_SKIP_HEADER');